# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_no', models.AutoField(primary_key=True, serialize=False)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('patient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=2000, null=True)),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('number_of_item', models.IntegerField(default=1)),
                ('amount_for_one', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
    ]
